
[[terms]]
== Terms and Definitions

The key words "*MUST*", "*MUST NOT*", "*REQUIRED*", "*SHALL*",
"*SHALL NOT*", "*SHOULD*", "*SHOULD NOT*", "*RECOMMENDED*",
"*NOT RECOMMENDED*", "*MAY*", and "*OPTIONAL*" in this document
are to be interpreted as described in BCP 14 <<RFC2119>> <<RFC8174>>
when, and only when, they appear in all capitals, as shown here.

The following terms and definitions apply to this document.

//=== General

bit string::
  an ordered sequence of 0s and 1s.

byte string::
an ordered sequence of bytes, where one byte contains 8 bits and the leftmost bit is the most significant bit.

elliptic curve point::
a point stem:[P in E(F_(q^m))(m >= 1)] is either a pair of field elements stem:[(x_P,y_P)], where stem:[x_P,y_P] satisfy the ecliptic curve equation, or the point at infinity stem:[O].

field element::
the elements of finite field stem:[F_(q^m)] ( stem:[m >= 1]).

message::
  a bit string of finite length. In this document, the message is the input to the hash algorithm.

plaintext::
  unencrypted information

ciphertext::
  data which has been transformed to hide its information content

encryption::
(invertible) transformation of data by a cryptographic algorithm to generate ciphertext, i.e. to hide the information content of the data

decryption::
the inverse process of the corresponding encryption

hash value::
  the output bit string of the hash algorithm given input of a message.

identity::
  information that can be used to confirm the identity of an entity, composed of non-repudiable information about the entity, such as its distinguished name, email address, identity card number, and telephone number

master key::
  topmost key in the key hierarchy of an identity–based cryptographic system, composed of the master private key and master public key. The master public key is publicly available, while the master private key is preserved by the KGC in secrecy. A user's private key is generated by the KGC using the master private key and the user's identity. In an identity–based cryptographic system, the master private key is usually generated by the KGC using random number generators; the master public key is generated with the master private key and system parameters.

NOTE: This specification uses a different master key for the signature system than that of the encryption system. The master key of the digital signature algorithm, which belongs to the signature system, is the signature master key. The master key of the key exchange protocol, key encapsulation mechanism and public key encryption algorithm, which all belong to the encryption system, is the encryption master key.

key generation center (KGC)::
trusted authority responsible for the selection of the system parameters, generation of master keys and generation of users' private keys within SM9 identity-based cryptographic algorithms.

key derivation function::
function that generates one or more shared secret keys from shared secrets and other parameters known to both entities

ECDLP:: discrete logarithm problem over elliptic curves

DLP:: discrete logarithm problem over finite fields

signed message::
group of data elements that consists of a message and its digital signature

signature key::
private key of the signer; the secret data element used by the signer in the digital signature generating process

signature master key::
topmost key in the key hierarchy of an identity–based cryptographic system, composed of the signature master private key and the signature master public key. The signature master public key is publicly available, while the signature master private key is kept secret by the KGC. The KGC generates the user's signature private key by using the signature master private key and the user's identity. In an identity–based cryptographic system, the signature master private key is usually generated by the KGC using random number generators, while the signature master public key is generated with the signature master private key and the system parameters

signature key generation center (SKGC)::
trusted authority responsible for the selection of system parameters, generation of the signature master keys, and generation of users' signature private keys (in this part)

// Key Exchange Protocol

key exchange::
scheme to exchange keys securely between communication entities, enables both entities to exchange keys securely for transmitting information over an insecure communication channel

key agreement::
process to generate a shared secret key among multiple users, where no user can determinate the value of the key beforehand

key confirmation from A to B::
assurance for user B that user A is in possession of the correct key

initiator::
entity which initiates the first round of message exchange in the protocol

responder::
entity that does not initiate the first round of message exchange in the protocol

encryption master key::
topmost key in the key hierarchy of an identity–based cryptographic system, composed of the encryption master private key and the encryption master public key.The encryption master public key is publicly available while the encryption master private key is kept secret by the KGC. The KGC generates the user's encryption private key by using the encryption master private key and the user's identity. In an identity–based cryptographic system, the encryption master private key is usually generated by the KGC using random number generators, while the encryption master public key is generated with the encryption master private key and the system parameters

encryption key generation center (EKGC)::
trusted authority responsible for the selection of system parameters, generation of the encryption master keys, and generation of users' encryption private keys (in this part)


// Public Key Encryption And Key Encapsulation

secret key::
key shared by both the sender and the receiver in a cryptographic system, unknown to any third party

message authentication code (MAC)::
authentication algorithm which is used to identify the source and check the integrity of the data by generating a section of code from a specific key and the message, where the function used to obtain the message authentication code is called the message authentication code function

