
[[symbols]]
== Symbols And Abbreviations

////
== Operators

$$bitlen(S)$$::
  The length of string $$S$$ in bits (e.g., bitlen(101) == 3).

$$S + T$$::
  addition of two 32-bit vectors $$S$$ and $$T$$ with a $$mod 2^32$$ bit
  wrap around.

$$S and T$$::
  bitwise "and" of two 32-bit vectors $$S$$ and $$T$$.
  $$S$$ and $$T$$ will always have the same length.

$$S or T$$::
  bitwise "or" of two 32-bit vectors $$S$$ and $$T$$.
  $$S$$ and $$T$$ will always have the same length.

$$S xor T$$::
  bitwise exclusive-or of two 32-bit vectors $$S$$ and $$T$$.
  $$S$$ and $$T$$ will always have the same length.

$$not(S)$$::
  bitwise "not" of a 32-bit vectors $$S$$.

$$a <<< i$$::
  32-bit bitwise cyclic shift on $$a$$ with $$i$$ bits shifted left.

$$S || T$$::
  String S concatenated with string T (e.g., 000 || 111 == 000111).

$$a <- S$$::
  Assignment operator of value $$S$$ to variable $$a$$.

$$num2str(i, n)$$::
  The n-bit string whose base-2 interpretation is $$i$$
  (e.g., num2str(14,4) == 1110 and num2str(1,2) == 01).
== Usage
////


=== General

The following symbols are used in this document.

A, B:: two users using the identity-based cryptographic system

stem:[cf]:: cofactor of the order of an elliptic curve relative to stem:[N]

stem:[cid]:: curve identifier used to distinguish the type of elliptic curve used, denoted by one byte

stem:[deg (f)]:: the degree of the polynomial stem:[f(x)]

stem:[d_1, d_2]:: two divisors of stem:[k]

stem:[E]:: an elliptic curve over finite fields

stem:[E(F_q)]:: a set consisting of all rational points (including the point at infinity stem:[O]) of the elliptic curve stem:[E] over the finite field stem:[F_q]

stem:[E(F_q)\[r\]]:: the set of stem:[r]-torsion points in stem:[E(F_q)], that is the torsion subgroup of stem:[E(F_q)] of order stem:[r]

stem:[e]:: a bilinear pairing from stem:[G_1 xx G_2] to stem:[G_T]

stem:[eid]:: bilinear pairing identifier used to distinguish the type of bilinear pairing used, denoted by one byte

stem:[F_p]:: a prime field with stem:[p] elements

stem:[F_q]:: a finite field with stem:[q] elements

stem:[F_q^()]:: the multiplicative group composed of all the nonzero elements in stem:[F_q]

stem:[F_(q^m)]:: the stem:[m]-dimensional extension field of the finite field stem:[F_q]

stem:[G_T]:: a multiplicative cyclic group of prime order stem:[N]

stem:[G_1]:: an additive cyclic group of prime order stem:[N]

stem:[G_2]:: an additive cyclic group of prime order stem:[N]

stem:[gcd(x,y)]:: the greatest common divisor of stem:[x] and stem:[y]

stem:[H_v()]:: a cryptographic hash function

stem:[H_1()], stem:[H_2()]:: cryptographic functions derived from the cryptographic hash function

stem:[ID_X]:: the identity of the user X that uniquely determines the public key of X

stem:[k]:: the embedding degree of the curve stem:[E(F_q)] relative to stem:[N], where stem:[N] is a prime factor of stem:[E(F_q)]

stem:[m]:: the degree of the finite field extension stem:[F_(q^m) // F_q]

stem:[M]:: the message in plaintext, to be signed or encrypted

stem:[mod f(x)]:: the operation of modulo the polynomial stem:[f(x)]

stem:[mod n]:: the operation of modulo stem:[n], for example, stem:[23 mod 7 = 2]

stem:[N]:: the order of the cyclic groups stem:[G_1], stem:[G_2] and stem:[G_T], which is a prime number greater than stem:[2^(191)]

stem:[O]:: the point at infinity or the zero point on an elliptic curve, which is the identity element of the elliptic curve additive group

stem:[P]:: stem:[P = (x_P,y_P)] is a nonzero point on an elliptic curve, where its coordinates stem:[x_P] and stem:[y_P] satisfy the elliptic curve equation

stem:[P_1]:: a generator of stem:[G_1]

stem:[P_2]:: a generator of stem:[G_2]

stem:[P + Q]:: addition of two points stem:[P] and stem:[Q] on the elliptic curve E

stem:[p]:: a prime number greater than stem:[2^(191)]

stem:[q]:: the number of elements in the finite field stem:[F_q]

stem:[x_P]:: the stem:[x]-coordinate of point stem:[P]

stem:[x vv y]:: the concatenation of stem:[x] and stem:[y], where stem:[x] and stem:[y] are bit strings or byte strings

stem:[x -= y( mod q)]:: stem:[x] and stem:[y] are congruent modulo stem:[q], that is stem:[x mod q = y mod q]

stem:[y_P]:: the stem:[y]-coordinate of point stem:[P]

stem:[E(K)]:: the number of points in stem:[E(K)], also called the order of the elliptic curve group stem:[E(K)], where stem:[K] is a finite field (including stem:[F_q] and stem:[F_(q^k)])

stem:[(: P :)]:: the cyclic group generated by the point stem:[P] on an elliptic curve

stem:[\[u\]P]:: the stem:[u] multiple of a point stem:[P] on an elliptic curve

////
This is from part 3
stem:[\[u\]P]:: the stem:[u] multiple of the element stem:[P] in the additive groups stem:[G_1] or stem:[G_2]
////

stem:[\[x,y\]]:: the set of integers which are not less than stem:[x] and not greater than stem:[y]

stem:[|~ x ~|]:: ceiling function that maps to the smallest integer not less than stem:[x], for example, stem:[|~ 7 ~| = 7], stem:[|~ 8.3 ~| = 9]

stem:[| __x__ |]:: floor function that maps to the largest integer not greater than stem:[x], for example, stem:[| __7__ | = 7], stem:[| __8.3__ | = 8]

stem:[\beta]:: twisted curve parameter

stem:[\Psi]:: a homomorphism from stem:[G_2] to stem:[G_1] satisfying stem:[P_1 = \Psi (P_2)]

stem:[o+]:: the bitwise XOR operator that operates on two bit strings of the same length

stem:[g^u]:: stem:[g] to the power of stem:[u],
where stem:[g]is an element in the multiplicative group stem:[G_T] and stem:[u]is a positive integer,
that is stem:[g^u = underset(ug's)(ubrace (g * g * cdots * g))]

stem:[hid]:: identifier of the private key generating function, denoted by one byte, selected and made public by the KGC (for a signature private key, the SKGC; for an encryption private key, the EKGC)

=== Digital Signature

The following symbols are used in <<dsa>>.

stem:[ds_X]:: signature private key of the user X


stem:[(h,S)]:: the sent signature

stem:[(h^',S^')]:: the received signature

stem:[M^']:: the message to be verified

stem:[P_(pub - s)]:: the signature master public key

stem:[ks]:: the signature master private key


=== Key Exchange Protocol And Public Key Encryption

The following symbols are used in <<kep>> and <<pke>>.

stem:[de_X]:: the encryption private key of user X

stem:[KDF()]:: the key derivation function

stem:[P_(pub - e)]:: the encryption master public key

stem:[r_A]:: the temporary key generated by the user A during the key exchange

stem:[r_B]:: the temporary key generated by the user B during the key exchange

stem:[SK_A], stem:[SK_B]: the shared secret key agreed in the key exchange protocol

stem:[ke]:: the encryption master private key

stem:[<P>]:: the cyclic group generated by the element stem:[P]

// public key encryption only

stem:[Dec()]:: block cipher decryption algorithm

stem:[Enc()]:: block cipher encryption algorithm

stem:[M']:: the message obtained by decryption

stem:[MAC()]:: the message authentication code function
