
[[dsa]]
== Digital Signature Algorithm

This section specifies an identity-based digital signature algorithm built upon pairings on elliptic curves, including the digital signature generation and verification algorithms together with their corresponding processes.

This section corresponds to the content of <<GMT-0044.2-2016>>.

=== Purpose

Specifically, this algorithm is used for a receiver to use the signer's identity to verify data integrity and the sender's identity; and for a third party to verify authenticity of a signature and of the signed message.

The signer possesses an identity and a corresponding private key for signing.

The signature private key is generated by the SKGC using the signature master private key and the signer's identity. The signer uses its signature private key to sign the message and to generate a digital signature. The verifier verifies the authenticity of the signature by using the signer's identity.

// TODO: what's this orphaned line?
//Before generating and verifying the signature, the message to be signed stem:[M] and the message to be verified stem:[M^']

=== Necessary System Parameters

System parameters listed in <<system-parameters>> as mandatory,
in addition to the following, are required:

* the generator stem:[P_1] is of the cyclic subgroup stem:[G_1] of stem:[E(F_(q^(d_1)))]
of order stem:[N] (where stem:[d_1] divides stem:[k]),

* the generator stem:[P_2] is of the cyclic subgroup of stem:[E(F_(q^(d_2 )))] of order stem:[N] (where stem:[d_2] divides stem:[k]),

* the parameters stem:[d_1], stem:[d_2], both of which are factors of stem:[k].

The homomorphism stem:[\Psi] from stem:[G_2] to stem:[G_1] is an optional parameter.

The range of the bilinear pairing stem:[e] is the multiplicative cyclic group
stem:[G_T] of order stem:[N].

Further description and verification of system parameters are provided
in <<system-parameters>>.


=== Auxiliary Functions Required

The following auxiliary functions are used in this section:

* cryptographic hash functions, and
* random number generators.

See <<aux-functions>> for details.

=== Private Key Generation

==== Generation Of The Signature Master Key

The SKGC generates a random number stem:[ks in \[1,N - 1\]]
as the signature master private key, computes the element
stem:[P_( pub - s) = \[ks \]P_2] in stem:[G_2] as the
signature master public key, and then the signature master key pair
is stem:[( ks ,P_( pub - s))]. The SKGC keeps stem:[ks].

The SKGC selects a one-byte signature private key generating function
identifier stem:[hid] and makes it public.

==== Generation Of A User's Signature Private Key

Let stem:[ID_A] denote the user A's identity.

To generate the signature private key stem:[ds_A]
of A, the SKGC first computes
stem:[t_1 = H_1(ID_A vv hid, N) + ks]
over the finite field stem:[F_N].

If stem:[t_1=0], it regenerates the signature master private key, computes the signature master public key and makes it public, and updates the existing signature private keys of users. Otherwise, it computes stem:[t_2=ks \dot t_1^(-1)], and then computes stem:[s_A=\[t_2 \] P_1].


=== Digital Signature Generation Algorithm

Let stem:[M] be the message to be signed. In order to obtain the signature stem:[(h,S)] of the message stem:[M], user A performs the following operations as signer:

A1: Compute the element stem:[g = e(P_1,P_( pub - s))] in the group stem:[G_T];

A2: Generate a random integer stem:[r in \[1,N - 1\]];

A3: Compute the element stem:[w = g^r] in the group stem:[G_T], and convert the data type of stem:[w] to a bit string as specified in Clauses 6.2.6 and 6.2.5 of <<GMT-0044.1-2016>>.

A4: Compute the integer stem:[h = H_2(M vv w,N)];

A5: Compute the integer stem:[l = (r - h) mod N]; if stem:[l = 0], go to Step A2;

A6: Compute the element stem:[S = \[l\]ds_A] in the group stem:[G_1];

A7: Convert the data type of stem:[h] to a byte string as specified in Clause 6.2.2 of <<GMT-0044.1-2016>>, convert the data type of stem:[S] to a byte string as specified in Clause 6.2.8 in <<GMT-0044.1-2016>>.Output stem:[(h,S)] as the signature of message stem:[M].

==== Process Diagram

The process of the digital signature generation algorithm is shown in Figure 1.

Figure 1: Digital signature generation process

=== Digital Signature Verification Algorithm

To verify the received message stem:[M^'] and its digital signature stem:[(h^',S^')], user stem:[B] performs the following operations as receiver:

B1: Convert the data type of stem:[h^']to an integer as specified in Clause 6.2.3 of <<GMT-0044.1-2016>>.Check whether stem:[h^' in \[1,N - 1\]] holds true. If it does not, the verification fails;

B2: Convert the data type of stem:[S^']to a point on the elliptic curve as specified in Clause 6.2.9 of <<GMT-0044.1-2016>>, then check whether stem:[S^' in G_1]holds true as specified in Section 4.5 of <<GMT-0044.1-2016>>. If it does not hold, the verification fails;

B3: Compute the element stem:[g = e(P_1,P_( pub - s))] in the group stem:[G_T];

B4: Compute the element stem:[t = g^(h^')]in the group stem:[G_T];

B5: Compute the integer stem:[h_1 = H_1(ID_A vv hid ,N)];

B6: Compute the element stem:[P = \[h_1\]P_2 + P_( pub - s)] in the group stem:[G_2];

B7: Compute the element stem:[u = e(S^',P)] in the group stem:[G_T] ;

B8: Compute the element stem:[w^' = u * t] in the group stem:[G_T].Convert the data type of stem:[w^'] to a bit string as specified in Clauses 6.2.6 and 6.2.5 of <<GMT-0044.1-2016>>;

B9: Compute an integer stem:[h_2 = H_2(M^' vv w^',N)] and check whether stem:[h_2 = h^'].If so, the signature is valid.Otherwise, the validation fails.

==== Process Diagram

The process of the digital signature verification algorithm is shown in Figure 2.

Figure 2: Digital signature verification process

