[#oid]
= Object Identifier

The Object Identifier for SM9 is identified through these OIDs.

== GM/T OIDs

=== SCA OID Prefix

All SM9 GM/T OIDs belong under the "1.2.156.10197" OID prefix,
registered by the Chinese Cryptography Standardization Technology
Committee ("CCSTC"), a committee under the SCA.  Its components are
described below in ASN.1 notation.

* "id-ccstc" `{iso(1) member-body(2) cn(156) ccstc(10197)}`

=== Hash Algorithms

These SM9 OIDs are assigned in <<GMT-0004-2012>> and described in
<<GBT.33560-2017>>.

"1.2.156.10197.1.400" for "Hash Algorithms":

* "id-hash" `{id-ccstc sm-scheme(1) hash(400)}`

"1.2.156.10197.1.401" for "Hash Algorithm: SM9 Algorithm":

* "id-hash-sm9" `{id-ccstc sm-scheme(1) sm9(401)}`

"1.2.156.10197.1.401.1" for "Hash Algorithm: SM9 Algorithm used
without secret key":

* "id-hash-sm9-nsk" `{id-hash-sm9 no-secret-key(1)}`

"1.2.156.10197.1.401.2" for "Hash Algorithm: SM9 Algorithm used with
secret key":

* "id-hash-sm9-sk" `{id-hash-sm9 secret-key(2)}`


=== Integrated Algorithms

These OIDs that involves SM9 are described in <<GBT.33560-2017>>.

"1.2.156.10197.1.500" for "Integrated Algorithms":

* "id-int" `{id-ccstc sm-scheme(1) integrated(500)}`

"1.2.156.10197.1.501"	for "Digital Signature: SM2 and SM9"

* "id-dsa-sm2sm9" `{id-int dsa-sm2sm9(501)}`

"1.2.156.10197.1.502"	for "Digital Signature: SM9 and SM9"

* "id-dsa-sm9sm9" `{id-int dsa-sm9sm9(502)}`

"1.2.156.10197.1.504"	for "Digital Signature: RSA and SM9"

* "id-dsa-rsasm9" `{id-int dsa-rsasm9(504)}`


=== Standard Identification

The "SM9 Hash Algorithm" standard is assigned the
"1.2.156.10197.6.1.1.4" OID in <<GMT-0004-2012>> and this assignment
is also described in <<GBT.33560-2017>>.

* "id-standard-sm9" `{id-ccstc standard(1) fundamental(1) algorithm(1) sm9(4)}`

Note that this OID is purely used for identifying the SM9 standard
itself.


== ISO OID

SM9 is assigned the OID "1.0.10118.3.0.65" ("id-dhf-SM9") in
<<ISO.IEC.10118-3>>. Its components are described below in ASN.1
notation.

* "is10118-3" `{iso(1) standard(0) hash-functions(10118) part3(3)}`

* "id-dhf" `{is10118-3 algorithm(0)}`

* "id-dhf-SM9" `{id-dhf sm9(65)}`

