= SM9 identity-based cryptographic algorithm, Part 2: Digital signature algorithm
:stem:

== Scope

This part of <<GMT-0044-2016>> specifies an identity-based digital signature algorithm built upon pairings on elliptic curves, including the digital signature generation and verification algorithms together with their corresponding processes.

This part of <<GMT-0044-2016>> is applicable for a receiver to use the signer's identity to verify data integrity and the sender's identity; and for a third party to verify authenticity of a signature and of the signed message.

== Normative references

The following documents are referred to in the text in such a way that some or all of their content constitutes requirements of this document. For dated references, only the edition cited applies. For undated references, the latest edition of the referenced document (including any amendments) applies.

GM/T 0004‒2016, SM3 cryptographic hash algorithm

GM/T 0044.1‒2016, SM9 identity-based cryptographic algorithms — Part 1: General

== Terms and definitions

For the purposes of this document, the following terms and definitions apply.

=== message

bit string of finite length

=== signed message

group of data elements that consists of a message and its digital signature

=== signature key

private key of the signer; the secret data element used by the signer in the digital signature generating process

=== signature master key

topmost key in the key hierarchy of an identity–based cryptographic system, composed of the signature master private key and the signature master public key. The signature master public key is publicly available, while the signature master private key is kept secret by the KGC. The KGC generates the user's signature private key by using the signature master private key and the user's identity. In an identity–based cryptographic system, the signature master private key is usually generated by the KGC using random number generators, while the signature master public key is generated with the signature master private key and the system parameters

=== identity

information that can be used to confirm the identity of an entity, composed of non-repudiable information about the entity, such as its distinguished name, email address, identity card number, and telephone number

=== key generation center (KGC)

trusted authority responsible for the selection of system parameters, generation of the signature master keys, and generation of users' signature private keys (in this part)

== Symbols

The following symbols apply to this part.

A, B: two users using the identity-based cryptographic system

stem:[cf]:: cofactor of the order of an elliptic curve relative to stem:[N]

stem:[cid]:: curve identifier that indicates the type of elliptic curve, denoted by one byte, where `0x10` represents an ordinary curve (a non-supersingular curve) over stem:[F_p]

stem:[ds_A]:: signature private key of the user A

stem:[e]:: a bilinear pairing from stem:[G_1 xx G_2] to stem:[G_T]

stem:[eid]:: bilinear pairing identifier to distinguish the type of the bilinear pairing stem:[e], denoted by one byte, where `0x01` represents the Tate pairing, `0x02` represents the Weil pairing, `0x03` represents the Ate pairing, and `0x04` represents the R-Ate pairing

stem:[G_T]:: a multiplicative cyclic group of prime order stem:[N]

stem:[G_1]:: an additive cyclic group of prime order stem:[N]

stem:[G_2]:: an additive cyclic group of prime order stem:[N]

stem:[g^u]:: stem:[g] to the power of stem:[u],
where stem:[g]is an element in the multiplicative group stem:[G_T] and stem:[u]is a positive integer,
that is stem:[g^u = underset(ug's)(ubrace (g * g * cdots * g))]

stem:[H_v()]:: a cryptographic hash function

stem:[H_1()], stem:[H_2()]:: cryptographic functions derived from the cryptographic hash function

stem:[hid]:: identifier of the signature private key generating function, denoted by one byte, selected and made public by the KGC

stem:[(h,S)]:: the sent signature

stem:[(h^',S^')]:: the received signature

stem:[ID_A]:: the identity of the user A that uniquely determines the public key of A

stem:[M]:: the message to be signed

stem:[M^']:: the message to be verified

stem:[mod n]:: the operation of modulo stem:[n], for example, stem:[23 mod 7 = 2]

stem:[N]:: the order of the cyclic groups stem:[G_1], stem:[G_2] and stem:[G_T], which is a prime number greater than stem:[2^(191)]

stem:[P_( pub - s)]:: the signature master public key

stem:[P_1]:: a generator of stem:[G_1]

stem:[P_2]:: a generator of stem:[G_2]

stem:[ks]:: the signature master private key

stem:[(: P :)]:: the cyclic group generated by the element
stem:[P]

stem:[\[u\]P]:: the stem:[u]multiple of the element
stem:[P]
 in the additive groups
stem:[G_1]
 or stem:[G_2]

stem:[|~ x ~|]:: ceiling function that maps to the smallest integer not less than stem:[x], for example, stem:[|~ 7 ~| = 7], stem:[|~ 8.3 ~| = 9]

stem:[| __x__ |]:: floor function that maps to the largest integer not greater than stem:[x], for example, stem:[| __7__ | = 7], stem:[| __8.3__ | = 8]

stem:[x || y]:: the concatenation of stem:[x] and stem:[y] , where
stem:[x] and stem:[y] are bit strings or byte strings

stem:[\[x,y\]]:: the set of integers which are not less than stem:[x] and not greater than stem:[y]

stem:[\beta]:: the twisted curve parameter

== Algorithm parameters and auxiliary functions
=== Overview

This part specifies an identity-based digital signature algorithm realized by pairings from elliptic curves. The signer possesses an identity and a corresponding private key for signing.The signature private key is generated by the KGC using the signature master private key and the signer's identity. The signer uses its signature private key to sign the message and to generate a digital signature.The verifier verifies the authenticity of the signature by using the signer's identity.

Before generating and verifying the signature, the message to be signed stem:[M] and the message to be verified stem:[M^']

=== System parameters

The system parameters include:

* the curve identifier stem:[cid] ,the parameters of the elliptic curve base field
stem:[F_q] ,the parameters of the elliptic curve equation
stem:[a]
 and
stem:[b] ,the twisted curve parameter
stem:[\beta]
 (if the least significant 4 bits of stem:[cid]is 2),the prime factor
stem:[N]
 of the order of the curve and the cofactor
stem:[cf]
 relative to
stem:[N] , the embedding degree
stem:[k] of the curve
stem:[E(F_q)]
 relative to
stem:[N], a generator
stem:[P_1]
 of the cyclic subgroup
stem:[G_1]

The range of the bilinear pairing stem:[e]
 is the multiplicative cyclic group
stem:[G_T] of order
stem:[N] .

For detailed descriptions of the system parameters as well as their verification, please refer to Clause 7 in GM/T 0044.1‒2016.

=== Generation of the signature master key and the user's signature private key

The KGC generates a random number stem:[ks in \[1,N - 1\]]
 as the signature master private key, computes the element
stem:[P_( pub - s) = \[ks \]P_2]
 in
stem:[G_2]
 as the signature master public key, and then the signature master key pair is stem:[( ks ,P_( pub - s))]. The KGC keeps
stem:[ks]

The KGC selects a one-byte signature private key generating function identifier stem:[hid]
 and makes it public.

Let stem:[ID_A] denote the user A's identity.To generate the signature private key stem:[ds_A]
 of A, the KGC first computes
stem:[\[\[ID_A || | hid, N) + ks \],\[t_1 = H_1\]\]]

=== Auxiliary functions
==== Overview

Two types of auxiliary functions are used in the identity-based digital signature algorithm specified in this part: cryptographic hash functions and random number generators.


==== Cryptographic hash functions
===== Cryptographic_hash_function stem:[H_v]

The output of the cryptographic hash function stem:[H_v()] is a
stem:[v] -bit hash value. This part adopts the cryptographic hash functions approved by the State Cryptography Administration such as the
SM3


===== Cryptographic_hash_function stem:[H_1]

The input of the cryptographic function stem:[H_1(Z,n)] is a bit string stem:[Z] and an integer stem:[n], and its output is an integer stem:[h_1 in \[1,n - 1\]].
stem:[H_1(Z,n)] invokes the cryptographic hash function stem:[H_v()] internally.
stem:[H_v()] is specified in 5.4.2.1.

*Cryptographic function* stem:[H_1(Z,n)]*:*

Input::a bit string stem:[Z] and an integer stem:[n].

Output:: an integer stem:[h_1 in \[1,n - 1\]].

Step 1: Initialize a 32-bit counter stem:[ct = 0x00000001];

Step 2: Compute stem:[hlen = 8 xx |~ (5 xx ( log_2n)) // 32 ~|];

Step 3: For stem:[i = 1]to stem:[|~ hlen // v ~|]:

Step 3.1: Compute stem:[Ha_i = H_v(0x01 || |Z| || ct )];

Step 3.2: stem:[ct]++;

Step 4: If stem:[hlen // v]is an integer, set stem:[(Ha ! )_( |~ hlen // v ~| ) = Ha_( |~ hlen // v ~| )]. Otherwise, set stem:[H(a ! )_( |~ hlen // v ~| )] to be the leftmost stem:[( hlen - (v xx | __hlen // v__ | ))]bits of stem:[Ha_( |~ hlen // v ~| )].

Step 5: Set stem:[Ha = Ha_1 || |Ha_2| || cdots || Ha_( |~ hlen // v ~| - 1) || H(a ! )_( |~ hlen // v ~| )]. Convert the data type of stem:[Ha] to integer as specified in Clauses 6.2.4 and 6.2.3 of GM/T 0044.1‒2016.

Step 6: Compute stem:[h_1 = (Ha mod (n - 1)) + 1].


===== Cryptographic_hash_function stem:[H_2]

The input of the cryptographic function stem:[H_2(Z,n)] is a bit string stem:[Z] and an integer stem:[n], and its output is an integer stem:[h_2 in \[1,n - 1\]]. stem:[H_2(Z,n)] invokes the cryptographic hash function stem:[H_v()] internally. stem:[H_v()] is specified in 5.4.2.1.

*Cryptographic function* stem:[H_2(Z,n)]*:*

Input::a bit string stem:[Z], an integer stem:[n].

Output:: an integer stem:[h_2 in \[1,n - 1\]].

Step 1: Initialize a 32-bit counter stem:[ct = 0x00000001];

Step 2: Compute stem:[hlen = 8 xx |~ (5 xx ( log_2n)) // 32 ~|];

Step 3: For stem:[i = 1]to stem:[|~ hlen // v ~|]:

Step 3.1: Compute stem:[Ha_i = H_v(0x02 || |Z| || ct )];

Step 3.2: stem:[ct]++;

Step 4: If stem:[hlen // v] is an integer, set stem:[H(a ! )_( |~ hlen // v ~| ) = Ha_( |~ hlen // v ~| )]. Otherwise, set stem:[H(a ! )_( |~ hlen // v ~| )] to be the leftmost stem:[( hlen - (v xx | __hlen // v__ | ))]bits of stem:[Ha_( |~ hlen // v ~| )].

Step 5: Set stem:[Ha = Ha_1 || |Ha_2| || cdots vv] stem:[Ha_( |~ hlen // v ~| - 1)] stem:[vv H(a ! )_( |~ hlen // v ~| )] . Convert the data type of stem:[Ha] to integer as specified in Clauses 6.2.4 and 6.2.3of GM/T 0044.1‒2016.

Step 6: Compute stem:[h_2 = (Ha mod (n - 1)) + 1].


==== Random number generators

This part adopts random number generators approved by the State Cryptography Administration.

== Digital signature generation algorithm and its process
=== Digital signature generation algorithm

Let stem:[M] be the message to be signed. In order to obtain the signature stem:[(h,S)]of the message stem:[M], user A performs the following operations as signer:

A1: Compute the element stem:[g = e(P_1,P_( pub - s))] in the group stem:[G_T];

A2: Generate a random integer stem:[r in \[1,N - 1\]];

A3: Compute the element stem:[w = g^r] in the group stem:[G_T], and convert the data type of stem:[w] to a bit string as specified in Clauses 6.2.6 and 6.2.5 of GM/T 0044.1‒2016.

A4: Compute the integer stem:[h = H_2(M || w,N)];

A5: Compute the integer stem:[l = (r - h) mod N]; if stem:[l = 0], go to Step A2;

A6: Compute the element stem:[S = \[l\]ds_A]in the group stem:[G_1];

A7: Convert the data type of stem:[h] to a byte string as specified in Clause 6.2.2 of GM/T 0044.1‒2016, convert the data type of stem:[S] to a byte string as specified in Clause 6.2.8 in GM/T 0044.1‒2016.Output stem:[(h,S)]as the signature of message stem:[M .]

=== Digital signature generation process

The process of the digital signature generation algorithm is shown in Figure 1.

Figure 1: Digital signature generation process

== Digital signature verification algorithm and its process

=== Digital signature verification algorithm

To verify the received message stem:[M^'] and its digital signature stem:[(h^',S^')], user stem:[B] performs the following operations as receiver:

B1: Convert the data type of stem:[h^']to an integer as specified in Clause 6.2.3 of GM/T 0044.1‒2016.Check whether stem:[h^' in \[1,N - 1\]]holds true.If it does not, the verification fails;

B2: Convert the data type of stem:[S^']to a point on the elliptic curve as specified in Clause 6.2.9 of GM/T 0044.1‒2016, then check whether stem:[S^' in G_1]holds true as specified in Section 4.5 of GM/T 0044.1‒2016.If it does not hold, the verification fails;

B3: Compute the element stem:[g = e(P_1,P_( pub - s))] in the group stem:[G_T];

B4: Compute the element stem:[t = g^(h^')]in the group stem:[G_T];

B5: Compute the integer stem:[h_1 = H_1(ID_A || hid, N)];

B6: Compute the element stem:[P = \[h_1\]P_2 + P_( pub - s)] in the group stem:[G_2];

B7: Compute the element stem:[u = e(S^',P)] in the group stem:[G_T] ;

B8: Compute the element stem:[w^' = u * t] in the group stem:[G_T].Convert the data type of stem:[w^'] to a bit string as specified in Clauses 6.2.6 and 6.2.5 of GM/T 0044.1‒2016;

B9: Compute an integer stem:[h_2 = H_2(M^' || w^',N)] and check whether stem:[h_2 = h^'].If so, the signature is valid.Otherwise, the validation fails.

=== Digital signature verification process

The process of the digital signature verification algorithm is shown in Figure 2.

Figure 2: Digital signature verification process
